### ISSUE TITLE
Exceptions Thrown

### ISSUE THREAD

**Issue by bsulliva** [avadev/AvaTax-REST-V2-DotNet-SDK#132]
Hello, I'm using the latest SDK version and the .net 4.5 version. Whenever my account does not authenticate an exception is thrown in the code and returned to me. If possible please return the actual error message as a JSON string.

2020-05-07 12:08:01,318 [10] ERROR Mouser.Services.OrdersService.OrderController [(null)] - Avalara.AvaTax.RestClient.AvaTaxError: Exception of type 'Avalara.AvaTax.RestClient.AvaTaxError' was thrown.
   at Avalara.AvaTax.RestClient.AvaTaxClient.<RestCallStringAsync>d__607.MoveNext() in C:\git\develop\AvaTax-REST-V2-DotNet-SDK\src\AvaTaxClient.cs:line 413
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Avalara.AvaTax.RestClient.AvaTaxClient.<RestCallAsync>d__599`1.MoveNext() in C:\git\develop\AvaTax-REST-V2-DotNet-SDK\src\AvaTaxClient.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Avalara.AvaTax.RestClient.AvaTaxClient.RestCall[T](String verb, AvaTaxPath relativePath, Object content) in C:\git\develop\AvaTax-REST-V2-DotNet-SDK\src\AvaTaxClient.cs:line 210
   at Avalara.AvaTax.RestClient.AvaTaxClient.CreateTransaction(String include, CreateTransactionModel model) in C:\git\develop\AvaTax-REST-V2-DotNet-SDK\src\AvaTaxApi.cs:line 8026

**Comment by gregwinterstein** [comment]
Isn't the error message available in the error field of the exception?
`...
catch (Avalara.AvaTax.RestClient.AvaTaxError ex)
{
    Console.WriteLine("Error: " + ex.error);
}
...`
